import { prisma } from '../../config/db.js';
import { RiskEngine } from '../risk/riskEngine.js';
import { OpenMeteoClient } from './openMeteoClient.js';
import {
  OpenMeteoResponse,
  NormalizedWeatherReading,
  WeatherSyncLocationResult,
  WeatherSyncReport
} from '../../types/index.js';

export class WeatherHydrologyService {
  /**
   * Normalizes meteorological data from Open-Meteo into an urban hydrologic EnvironmentalReading.
   * Couples precipitation with physical location terrain (elevation, catchment basin, and drainage status).
   */
  public static normalizeWeatherData(
    weather: OpenMeteoResponse,
    location: {
      id: string;
      name: string;
      elevationMeters: number;
      catchmentAreaKm2: number;
      drainageCondition: string;
      readings?: Array<{
        rainfallMm: number;
        waterLevelCm: number;
        drainageFlowPct: number;
      }>;
    },
    simulatedRainfall?: number
  ): NormalizedWeatherReading {
    const prevReading = location.readings && location.readings.length > 0 ? location.readings[0] : null;

    // 1. Determine Rainfall Intensity (mm/h)
    // If an operator specified a simulation override, use that; otherwise calculate from Open-Meteo
    let rainfallMm = 0;
    if (typeof simulatedRainfall === 'number' && !isNaN(simulatedRainfall)) {
      rainfallMm = Math.max(0, simulatedRainfall);
    } else {
      // Open-Meteo current.precipitation is mm over interval.
      // If interval is 900s (15 min), 4x represents hourly mm/h precipitation intensity.
      const intervalSec = weather.current.interval || 900;
      const hoursFactor = 3600 / intervalSec;
      const currentRate = (weather.current.precipitation || weather.current.rain || 0) * hoursFactor;

      // Check peak hourly precipitation if current interval is between rain bursts
      let peakHourly = 0;
      if (weather.hourly && Array.isArray(weather.hourly.precipitation)) {
        const recentHourly = weather.hourly.precipitation.slice(0, 3);
        peakHourly = Math.max(...recentHourly.filter(n => typeof n === 'number'), 0);
      }

      rainfallMm = Number(Math.max(currentRate, peakHourly).toFixed(1));
    }

    // 2. Physical Hydrological Factors
    // Drainage efficiency coefficient (fraction of runoff effectively cleared)
    let drainageEfficiency = 0.55;
    const cond = (location.drainageCondition || '').toLowerCase();
    if (cond.includes('critical') || cond.includes('choked')) {
      drainageEfficiency = 0.15;
    } else if (cond.includes('poor')) {
      drainageEfficiency = 0.25;
    } else if (cond.includes('moderate')) {
      drainageEfficiency = 0.50;
    } else if (cond.includes('good')) {
      drainageEfficiency = 0.85;
    }

    // Topographic depression multiplier
    // Locations below ground grade (e.g. Railway Underpass at -1.8m) accumulate runoff from surrounding area
    let depressionMultiplier = 1.0;
    if (location.elevationMeters <= -1.0) {
      depressionMultiplier = 1.6;
    } else if (location.elevationMeters <= 0.0) {
      depressionMultiplier = 1.25;
    } else if (location.elevationMeters >= 2.0) {
      depressionMultiplier = 0.65; // Ridge or elevated canal flume sheds water quickly
    }

    const catchmentKm2 = location.catchmentAreaKm2 || 1.8;

    // 3. Compute Inundation Depth (waterLevelCm)
    let waterLevelCm = 0;
    const prevWaterLevel = prevReading ? prevReading.waterLevelCm : 0;

    if (rainfallMm > 0) {
      // Inflow rate generated by precipitation over the catchment area pooling into depression
      const runoffInflow = (rainfallMm * catchmentKm2 * depressionMultiplier) / 10;
      // Net accumulation after drainage discharge
      const netRunoff = runoffInflow * (1 - drainageEfficiency * 0.7);

      if (prevReading) {
        // Continuity: blend previous depth with new inflow
        waterLevelCm = Math.min(65, Math.max(2, prevWaterLevel * 0.88 + netRunoff * 0.6));
      } else {
        waterLevelCm = Math.min(65, Math.max(2, netRunoff * 1.2));
      }
    } else {
      // In dry / zero precipitation conditions: water recedes through gravity drainage
      if (prevWaterLevel > 5) {
        const recessionFactor = drainageEfficiency >= 0.7 ? 0.65 : 0.82;
        waterLevelCm = Math.max(0, prevWaterLevel * recessionFactor);
      } else {
        // Baseline dry clearance (0 to 3 cm)
        waterLevelCm = location.elevationMeters < 0 ? 2.0 : 0.0;
      }
    }

    waterLevelCm = Number(waterLevelCm.toFixed(1));

    // 4. Determine Water Level Trend & Rise Rate
    let waterLevelTrend: 'RISING' | 'STABLE' | 'RECEDING' = 'STABLE';
    let riseRate = '0cm / 15min';

    const delta = prevReading ? waterLevelCm - prevWaterLevel : (rainfallMm > 15 ? 4.0 : 0);
    if (delta >= 1.5) {
      waterLevelTrend = 'RISING';
      riseRate = `+${Math.abs(delta).toFixed(1)}cm / 15min`;
    } else if (delta <= -1.5) {
      waterLevelTrend = 'RECEDING';
      riseRate = `-${Math.abs(delta).toFixed(1)}cm / 15min`;
    } else {
      waterLevelTrend = 'STABLE';
      riseRate = '0cm / 15min';
    }

    // 5. Drainage Flow Percentage (Operational Capacity)
    let drainageFlowPct = Math.round(drainageEfficiency * 100);
    if (rainfallMm >= 60) {
      // Surcharge reduces effective discharge capacity
      drainageFlowPct = Math.max(10, drainageFlowPct - 15);
    }

    return {
      rainfallMm,
      waterLevelCm,
      drainageFlowPct,
      waterLevelTrend,
      riseRate,
      rawTemperature: weather.current.temperature_2m,
      rawHumidity: weather.current.relative_humidity_2m,
      rawWindSpeed: weather.current.wind_speed_10m,
      weatherCode: weather.current.weather_code
    };
  }

  /**
   * Synchronizes live weather for a single location:
   * 1. Fetches location from Supabase
   * 2. Calls Open-Meteo API
   * 3. Normalizes into EnvironmentalReading
   * 4. Persists EnvironmentalReading into Supabase
   * 5. Runs RiskEngine
   * 6. Persists RiskAssessment into Supabase
   */
  public static async syncLocation(
    locationId: string,
    options?: { simulatedRainfall?: number }
  ): Promise<WeatherSyncLocationResult> {
    // 1. Fetch location from Supabase PostgreSQL
    const location = await prisma.location.findUnique({
      where: { id: locationId },
      include: {
        readings: {
          orderBy: { timestamp: 'desc' },
          take: 1
        },
        riskAssessments: {
          orderBy: { evaluatedAt: 'desc' },
          take: 1
        }
      }
    });

    if (!location) {
      throw new Error(`Location with ID '${locationId}' not found in database.`);
    }

    const previousRiskScore = location.riskAssessments[0]?.riskScore;

    // 2. Fetch live weather from Open-Meteo
    const weatherData = await OpenMeteoClient.getForecast(location.latitude, location.longitude);

    // 3. Normalize into EnvironmentalReading
    const normalized = this.normalizeWeatherData(weatherData, location, options?.simulatedRainfall);

    // 4. Persist EnvironmentalReading to Supabase PostgreSQL
    const readingRecord = await prisma.environmentalReading.create({
      data: {
        locationId: location.id,
        rainfallMm: normalized.rainfallMm,
        waterLevelCm: normalized.waterLevelCm,
        drainageFlowPct: normalized.drainageFlowPct,
        waterLevelTrend: normalized.waterLevelTrend,
        riseRate: normalized.riseRate,
        timestamp: new Date()
      }
    });

    // 5. Execute existing RiskEngine
    const riskResult = RiskEngine.calculateFloodRisk({
      rainfallMm: normalized.rainfallMm,
      waterLevelCm: normalized.waterLevelCm,
      drainageCondition: location.drainageCondition,
      historicalIncidents: location.historicalIncidents
    });

    // 6. Persist RiskAssessment to Supabase PostgreSQL
    const assessmentRecord = await prisma.riskAssessment.create({
      data: {
        locationId: location.id,
        riskScore: riskResult.riskScore,
        riskLevel: riskResult.riskLevel,
        rainfallScore: riskResult.components.rainfallComponent,
        waterLevelScore: riskResult.components.waterLevelComponent,
        drainageScore: riskResult.components.drainageComponent,
        historyScore: riskResult.components.historyComponent,
        contributingFactors: riskResult.factors as any,
        recommendedActions: riskResult.recommendedActions as any,
        evaluatedAt: new Date()
      }
    });

    return {
      locationId: location.id,
      locationName: location.name,
      coordinates: {
        latitude: location.latitude,
        longitude: location.longitude
      },
      weather: {
        temperature: weatherData.current.temperature_2m,
        humidity: weatherData.current.relative_humidity_2m,
        precipitation: weatherData.current.precipitation,
        rain: weatherData.current.rain,
        windSpeed: weatherData.current.wind_speed_10m,
        weatherCode: weatherData.current.weather_code,
        observedAt: weatherData.current.time
      },
      reading: {
        id: readingRecord.id,
        rainfallMm: readingRecord.rainfallMm,
        waterLevelCm: readingRecord.waterLevelCm,
        drainageFlowPct: readingRecord.drainageFlowPct,
        waterLevelTrend: readingRecord.waterLevelTrend,
        riseRate: readingRecord.riseRate,
        timestamp: readingRecord.timestamp.toISOString()
      },
      assessment: {
        id: assessmentRecord.id,
        riskScore: assessmentRecord.riskScore,
        riskLevel: assessmentRecord.riskLevel as any,
        components: riskResult.components,
        factorsCount: riskResult.factors.length,
        actionsCount: riskResult.recommendedActions.length
      },
      previousRiskScore
    };
  }

  /**
   * Synchronizes all active locations in Supabase with live Open-Meteo weather.
   */
  public static async syncAllLocations(options?: {
    locationId?: string;
    simulatedRainfall?: number;
  }): Promise<WeatherSyncReport> {
    const syncTimestamp = new Date().toISOString();

    // If a specific locationId was requested, sync only that one
    if (options?.locationId) {
      const single = await this.syncLocation(options.locationId, {
        simulatedRainfall: options.simulatedRainfall
      });
      return {
        success: true,
        syncTimestamp,
        provider: 'Open-Meteo Weather API',
        summary: {
          totalLocations: 1,
          syncedLocations: 1,
          failedLocations: 0
        },
        results: [single]
      };
    }

    // Retrieve all locations from database
    const locations = await prisma.location.findMany({
      select: { id: true, name: true }
    });

    const results: WeatherSyncLocationResult[] = [];
    const errors: Array<{ locationId: string; error: string }> = [];

    for (const loc of locations) {
      try {
        const res = await this.syncLocation(loc.id, {
          simulatedRainfall: options?.simulatedRainfall
        });
        results.push(res);
      } catch (err: any) {
        console.error(`Weather sync failed for location '${loc.name}' (${loc.id}):`, err.message);
        errors.push({
          locationId: loc.id,
          error: err.message || 'Unknown synchronization failure'
        });
      }
    }

    return {
      success: errors.length === 0,
      syncTimestamp,
      provider: 'Open-Meteo Weather API',
      summary: {
        totalLocations: locations.length,
        syncedLocations: results.length,
        failedLocations: errors.length
      },
      results,
      errors: errors.length > 0 ? errors : undefined
    };
  }
}
